directories:
  profiles: profiles

ontologies:
  - id: phenio-flat
  - id: phenio-release
    mirror_from: https://github.com/monarch-initiative/phenio/releases/latest/download/phenio.owl.gz
  - id: phenio-equivalent
  - id: phenio-monarch
  - id: upheno1
    mirror_from: https://raw.githubusercontent.com/obophenotype/upheno/refs/heads/master/upheno.owl
  - id: hp
    mirror_from: http://purl.obolibrary.org/obo/hp.owl
    parent_term: HP:0000118
  - id: mp
    mirror_from: http://purl.obolibrary.org/obo/mp.owl
    parent_term: MP:0000001
  - id: zp
    mirror_from: http://purl.obolibrary.org/obo/zp.owl
    parent_term: ZP:0000000
  - id: fbcv
    mirror_from: http://purl.obolibrary.org/obo/dpo.owl
    parent_term: FBcv:0001347
  - id: xpo
    mirror_from: http://purl.obolibrary.org/obo/xpo.owl
    parent_term: XPO:00000000

semantic_similarity_profiles:

  ### PHENIO - LATTICE/RELEASE

  #- subset: all
  #  method: semsimian
  #  ontology: phenio-release
  #  threshold: 0.4
  #  branches:
  #    subject: UPHENO:0001001
  #    object: UPHENO:0001001
  - subset: hp-mp
    method: semsimian
    ontology: phenio-release
    threshold: 0.4
    branches:
      subject: UPHENO:0001001
      object: UPHENO:0001001
    prefixes:
      subject: hp
      object: mp
  - subset: hp-hp
    method: semsimian
    ontology: phenio-release
    threshold: 0.4
    branches:
      subject: UPHENO:0001001
      object: UPHENO:0001001
    prefixes:
      subject: hp
      object: hp
  - subset: hp-zp
    method: semsimian
    ontology: phenio-release
    threshold: 0.4
    branches:
      subject: UPHENO:0001001
      object: UPHENO:0001001
    prefixes:
      subject: hp
      object: zp
  

  ### UPHENO 1 (ORIGINAL)
  
  #- subset: all
  #  method: semsimian
  #  ontology: upheno1
  #  threshold: 0.4
  #  branches:
  #    subject: UPHENO:0001001
  #    object: UPHENO:0001001
    method: semsimian
    ontology: upheno1
    threshold: 0.4
    branches:
      subject: UPHENO:0001001
      object: UPHENO:0001001
    prefixes:
      subject: hp
      object: zp

    method: semsimian
    ontology: upheno1
    threshold: 0.4
    branches:
      subject: UPHENO:0001001
      object: UPHENO:0001001
    prefixes:
      subject: hp
      object: zp
  
  ### PHENIO - MONARCH

  - subset: hp-hp
    method: semsimian
    ontology: phenio-monarch
    ic: phenio_monarch_hp_ic.tsv
    threshold: 0.4
    prefixes:
      subject: hp
      object: hp
  - subset: hp-mp
    method: semsimian
    ontology: phenio-monarch
    ic: phenio_monarch_hp_mp_ic.tsv
    threshold: 0.4
    prefixes:
      subject: hp
      object: mp
  - subset: hp-zp
    method: semsimian
    ontology: phenio-monarch
    ic: phenio_monarch_hp_zp_ic.tsv
    threshold: 0.4
    prefixes:
      subject: hp
      object: zp
  - subset: hp-xpo
    method: semsimian
    ontology: phenio-monarch
    threshold: 0.4
    ic: phenio_monarch_hp_xpo_ic.tsv
    prefixes:
      subject: hp
      object: xpo
  - subset: hp-hp
    method: semsimian
    ontology: phenio-monarch
    threshold: 0.4
    prefixes:
      subject: hp
      object: hp
  - subset: hp-mp
    method: semsimian
    ontology: phenio-monarch
    threshold: 0.4
    prefixes:
      subject: hp
      object: mp
  - subset: hp-zp
    method: semsimian
    ontology: phenio-monarch
    threshold: 0.4
    prefixes:
      subject: hp
      object: zp
  - subset: hp-xpo
    method: semsimian
    ontology: phenio-monarch
    threshold: 0.4
    prefixes:
      subject: hp
      object: xpo
  - subset: hp-hp
    method: semsimian
    ontology: phenio-monarch
    threshold: 0.7
    prefixes:
      subject: hp
      object: hp
  - subset: hp-mp
    method: semsimian
    ontology: phenio-monarch
    threshold: 0.7
    prefixes:
      subject: hp
      object: mp
  - subset: hp-zp
    method: semsimian
    ontology: phenio-monarch
    threshold: 0.7
    prefixes:
      subject: hp
      object: zp
  - subset: hp-xpo
    method: semsimian
    ontology: phenio-monarch
    threshold: 0.7
    prefixes:
      subject: hp
      object: xpo
  - subset: hp-fbcv
    method: semsimian
    ontology: phenio-monarch
    threshold: 0.7
    prefixes:
      subject: hp
      object: fbcv
  #- subset: hp-mp
  #  method: cosine
  #  ontology: phenio-monarch
  #  threshold: 0.4
  #  branches:
  #     subject: UPHENO:0001001
  #     object: UPHENO:0001001
  #  prefixes:
  #     subject: hp
  #     object: mp

  #### PHENIO-FLAT

  - subset: hp-hp
    method: semsimian
    ontology: phenio-flat
    threshold: 0.4
    prefixes:
      subject: hp
      object: hp
  - subset: hp-mp
    method: semsimian
    ontology: phenio-flat
    threshold: 0.4
    prefixes:
      subject: hp
      object: mp
  - subset: hp-zp
    method: semsimian
    ontology: phenio-flat
    threshold: 0.4
    prefixes:
      subject: hp
      object: zp
  

#### PHENIO-EQUIVALENT

  - subset: hp-hp
    method: semsimian
    ontology: phenio-equivalent
    threshold: 0.4
    prefixes:
      subject: hp
      object: hp
  - subset: hp-mp
    method: semsimian
    ontology: phenio-equivalent
    threshold: 0.4
    prefixes:
      subject: hp
      object: mp
  - subset: hp-zp
    method: semsimian
    ontology: phenio-equivalent
    threshold: 0.4
    prefixes:
      subject: hp
      object: zp
